AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - method_call

require:
  - rubocop-minitest
  - rubocop-rake
